def count_motifs(dna, lengths):
    motifs_count_by_length = {length: {} for length in lengths}
    for length in lengths:
        for i in range(len(dna) - length + 1):
            motif = dna[i:i+length]
            if motif in motifs_count_by_length[length]:
                motifs_count_by_length[length][motif] += 1
            else:
                motifs_count_by_length[length][motif] = 1
    return motifs_count_by_length

dna_string = "CCACATCACTTACTACCCGGTCTCAATGGCCAACATGGAAATTAAGGCTTAACCGGCATTCAACGGCTTCCCACCGGATCTTACATGGATAACACTCGGTACCAACATGGTTTACCTCCGGCCACTCCTCGGAACAATACAGGTTATTACCCGGCATTTCCTTGGTAATATCCTGGCTTATTCAAGGCCTTCTCACGGTACCTAAATGGCTTTATTCCGGTTCTCAATTGGCCAATTCCAGGAATTCTCCCGGTAATCTAAAGGCACTTATTCGGTTCCTCCATGGTCCTTTACTGGCCTCCCCACGGTCCACATCTGGTTACTTATCGGCTCCTCCAAGGTATCTTATCGGACCACTCTCGGTCTCCCCTTGGCACAACACTGGTATACCAACGGCACTTTCTCGGATCACTCAAGGAACATAAAAGGTTCCCACTTGGTTCCTAACAGGATAATCATAGGCAACCCACAGGCCAAATTAAGGTCACCCAACGGAATTATCAAGGACATATCTTGGATAACCTTAGGTTCCTATACGGCCTTATCTTGGCTCATCTCTGGCATACTCCAGGCAATCATCCGGCTATAACCTGGTCCTAAATTGGTCAAACTTAGGATAATAAATGGCCTCTTAACGGATCCAAATAGGAACCCTCATGGACCCTTACTGGACCTAACACGGTTCCTCACAGGCTCTCATAAGGATCACCACTGGATCACTCATGGTATACCCTAGGTCAAATCTAGGCTTATATTAGGTAACAACCAGGTAATTCATCGGCCCTAAACCGGAATCATCCCGGACCACACACGGACTCATAATGGCAATTTACCGGTCTCCATAAGGCTCACTATAGGCCTCCCATCGGCATCTTCATGGAACCTCTTAGGACAAACCCAGGACACTCACAGGTCTTCTATTGGACCTTCATTGGAACCTTTCTGGAATCATACGGATCATATGGTAAACTAGGATCCCTAGGTATCACAACTACCTCACAAAAAAAAAA"

motif_lengths = [3, 4, 5, 6, 7]
motifs_counts = count_motifs(dna_string, motif_lengths)

# 输出结果
for length in motif_lengths:
    print(f"Length {length} motifs:")
    for motif, count in motifs_counts[length].items():
        print(f"{motif}: {count}")
